TeacherHelper/Areas/Admin/Controllers/TeacherController.cs
using Microsoft.AspNetCore.Mvc;
using TeacherHelper.DataAccess.Repository.IRepository;
using TeacherHelper.Models;

namespace TeacherHelperWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class TeacherController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public TeacherController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            IEnumerable<Teacher> objTeacherList = _unitOfWork.Teacher.GetAll();
            return View();
        }

        //GET
        public IActionResult Upsert(int? id)
        {
            Teacher teacher = new();
            if (id == null || id == 0)
            {
                return View(teacher);
            }
            else
            {
                teacher = _unitOfWork.Teacher.GetFirstOrDefault(u => u.Id == id);

                if (teacher == null)
                {
                    return NotFound();
                }
                return View(teacher);
            }


        }

        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            var teacherList = _unitOfWork.Teacher.GetAll();
            return Json(new { data = teacherList });
        }
        #endregion

    }
}

TeacherHelper/Areas/Admin/Views/Teacher/Index.cshtml
<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Teacher List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Teacher" asp-action="Upsert" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> &nbsp; Add New Teacher
            </a>
            <br/><br/>
        </div>
    </div>

    <table id="tblData" class="table table-bordered table-striped" style="width: 100%">
        <thead>
        <tr>
            <th>FirstName</th>
            <th>LastName</th>
            <th>Grades</th>
            <th></th>
        </tr>
        </thead>
   
    
    

    </table>
</div>

@section Scripts
{
    <script src="~/js/teacher.js"></script>
}